"""OAuth flow endpoints for HubSpot, Pipedrive, Attio, and Zoho."""

import hashlib
import hmac
import logging
import time
import urllib.parse
from datetime import datetime, timedelta, timezone
from typing import Any

import httpx
from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import RedirectResponse
from supabase import Client

from app.config import Settings, get_settings
from app.middleware.auth import get_current_user, get_supabase

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/auth", tags=["auth"])

# OAuth state expires after 10 minutes
_STATE_MAX_AGE_SECONDS = 600


def _sign_oauth_state(user_id: str, secret: str) -> str:
    """Create a signed OAuth state: user_id:timestamp:signature.

    Prevents CSRF by ensuring the callback state was generated by us
    and hasn't been tampered with.
    """
    ts = str(int(time.time()))
    payload = f"{user_id}:{ts}"
    sig = hmac.new(secret.encode(), payload.encode(), hashlib.sha256).hexdigest()[:16]
    return f"{payload}:{sig}"


def _verify_oauth_state(state: str, secret: str) -> str:
    """Verify and extract user_id from a signed OAuth state.

    Returns:
        The user_id if valid.

    Raises:
        HTTPException: If state is invalid, expired, or tampered with.
    """
    parts = state.split(":")
    if len(parts) != 3:
        raise HTTPException(status_code=400, detail="Invalid OAuth state")

    user_id, ts_str, sig = parts

    # Check signature
    payload = f"{user_id}:{ts_str}"
    expected_sig = hmac.new(
        secret.encode(), payload.encode(), hashlib.sha256
    ).hexdigest()[:16]
    if not hmac.compare_digest(sig, expected_sig):
        raise HTTPException(status_code=400, detail="Invalid OAuth state signature")

    # Check expiry
    try:
        ts = int(ts_str)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid OAuth state timestamp")

    if time.time() - ts > _STATE_MAX_AGE_SECONDS:
        raise HTTPException(status_code=400, detail="OAuth state expired")

    return user_id


# ---------------------------------------------------------------------------
# HubSpot OAuth
# ---------------------------------------------------------------------------

HUBSPOT_SCOPES = [
    "crm.objects.contacts.write",
    "crm.objects.contacts.read",
    "crm.objects.companies.write",
    "crm.objects.companies.read",
    "crm.objects.deals.write",
    "crm.objects.deals.read",
]


@router.get("/hubspot")
async def hubspot_auth(
    user: Any = Depends(get_current_user),
    settings: Settings = Depends(get_settings),
) -> RedirectResponse:
    """Redirect the user to HubSpot's OAuth consent screen."""
    params = {
        "client_id": settings.hubspot_client_id,
        "redirect_uri": settings.hubspot_redirect_uri,
        "scope": " ".join(HUBSPOT_SCOPES),
        "state": _sign_oauth_state(user.id, settings.supabase_service_role_key),
    }
    url = f"https://app.hubspot.com/oauth/authorize?{urllib.parse.urlencode(params)}"
    return RedirectResponse(url=url)


@router.get("/hubspot/callback")
async def hubspot_callback(
    code: str = Query(...),
    state: str = Query(""),
    settings: Settings = Depends(get_settings),
    supabase: Client = Depends(get_supabase),
) -> RedirectResponse:
    """Exchange the HubSpot auth code for tokens and store the connection."""
    user_id = _verify_oauth_state(state, settings.supabase_service_role_key)

    # Exchange code for tokens
    async with httpx.AsyncClient(timeout=15.0) as client:
        response = await client.post(
            "https://api.hubapi.com/oauth/v3/token",
            data={
                "grant_type": "authorization_code",
                "client_id": settings.hubspot_client_id,
                "client_secret": settings.hubspot_client_secret,
                "redirect_uri": settings.hubspot_redirect_uri,
                "code": code,
            },
        )

    if response.status_code != 200:
        logger.error("HubSpot token exchange failed: %s", response.text)
        raise HTTPException(
            status_code=400,
            detail="Failed to authenticate with HubSpot. Please try again.",
        )

    tokens = response.json()
    expires_at = (
        datetime.now(timezone.utc) + timedelta(seconds=tokens.get("expires_in", 21600))
    ).isoformat()

    # Upsert connection
    connection_data = {
        "user_id": user_id,
        "service": "hubspot",
        "access_token": tokens["access_token"],
        "refresh_token": tokens["refresh_token"],
        "token_expires_at": expires_at,
        "metadata": {},
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }

    # Check if connection already exists
    existing = (
        supabase.table("connections")
        .select("id")
        .eq("user_id", user_id)
        .eq("service", "hubspot")
        .execute()
    )

    if existing.data:
        supabase.table("connections").update(connection_data).eq(
            "id", existing.data[0]["id"]
        ).execute()
    else:
        supabase.table("connections").insert(connection_data).execute()

    redirect_url = f"{settings.frontend_url}/connections?connected=hubspot"
    return RedirectResponse(url=redirect_url)


# ---------------------------------------------------------------------------
# Pipedrive OAuth
# ---------------------------------------------------------------------------

@router.get("/pipedrive")
async def pipedrive_auth(
    user: Any = Depends(get_current_user),
    settings: Settings = Depends(get_settings),
) -> RedirectResponse:
    """Redirect the user to Pipedrive's OAuth consent screen."""
    params = {
        "client_id": settings.pipedrive_client_id,
        "redirect_uri": settings.pipedrive_redirect_uri,
        "state": _sign_oauth_state(user.id, settings.supabase_service_role_key),
    }
    url = f"https://oauth.pipedrive.com/oauth/authorize?{urllib.parse.urlencode(params)}"
    return RedirectResponse(url=url)


@router.get("/pipedrive/callback")
async def pipedrive_callback(
    code: str = Query(...),
    state: str = Query(""),
    settings: Settings = Depends(get_settings),
    supabase: Client = Depends(get_supabase),
) -> RedirectResponse:
    """Exchange the Pipedrive auth code for tokens and store the connection."""
    user_id = _verify_oauth_state(state, settings.supabase_service_role_key)

    # Exchange code for tokens
    async with httpx.AsyncClient(timeout=15.0) as client:
        response = await client.post(
            "https://oauth.pipedrive.com/oauth/token",
            data={
                "grant_type": "authorization_code",
                "redirect_uri": settings.pipedrive_redirect_uri,
                "code": code,
            },
            auth=(settings.pipedrive_client_id, settings.pipedrive_client_secret),
        )

    if response.status_code != 200:
        logger.error("Pipedrive token exchange failed: %s", response.text)
        raise HTTPException(
            status_code=400,
            detail="Failed to authenticate with Pipedrive. Please try again.",
        )

    tokens = response.json()
    expires_at = (
        datetime.now(timezone.utc) + timedelta(seconds=tokens.get("expires_in", 3600))
    ).isoformat()

    # Extract company_domain from the API domain returned by Pipedrive
    api_domain = tokens.get("api_domain", "")
    # api_domain looks like "https://companyname.pipedrive.com"
    company_domain = ""
    if api_domain:
        try:
            parsed = urllib.parse.urlparse(api_domain)
            hostname = parsed.hostname or ""
            # Extract subdomain: "companyname" from "companyname.pipedrive.com"
            if hostname.endswith(".pipedrive.com"):
                company_domain = hostname.replace(".pipedrive.com", "")
        except Exception:
            company_domain = ""

    # Upsert connection
    connection_data = {
        "user_id": user_id,
        "service": "pipedrive",
        "access_token": tokens["access_token"],
        "refresh_token": tokens["refresh_token"],
        "token_expires_at": expires_at,
        "metadata": {"company_domain": company_domain},
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }

    existing = (
        supabase.table("connections")
        .select("id")
        .eq("user_id", user_id)
        .eq("service", "pipedrive")
        .execute()
    )

    if existing.data:
        supabase.table("connections").update(connection_data).eq(
            "id", existing.data[0]["id"]
        ).execute()
    else:
        supabase.table("connections").insert(connection_data).execute()

    redirect_url = f"{settings.frontend_url}/connections?connected=pipedrive"
    return RedirectResponse(url=redirect_url)


# ---------------------------------------------------------------------------
# Attio OAuth
# ---------------------------------------------------------------------------

@router.get("/attio")
async def attio_auth(
    user: Any = Depends(get_current_user),
    settings: Settings = Depends(get_settings),
) -> RedirectResponse:
    """Redirect the user to Attio's OAuth consent screen."""
    params = {
        "response_type": "code",
        "client_id": settings.attio_client_id,
        "redirect_uri": settings.attio_redirect_uri,
        "state": _sign_oauth_state(user.id, settings.supabase_service_role_key),
    }
    url = f"https://app.attio.com/authorize?{urllib.parse.urlencode(params)}"
    return RedirectResponse(url=url)


@router.get("/attio/callback")
async def attio_callback(
    code: str = Query(...),
    state: str = Query(""),
    settings: Settings = Depends(get_settings),
    supabase: Client = Depends(get_supabase),
) -> RedirectResponse:
    """Exchange the Attio auth code for a token and store the connection."""
    user_id = _verify_oauth_state(state, settings.supabase_service_role_key)

    # Exchange code for token
    async with httpx.AsyncClient(timeout=15.0) as client:
        response = await client.post(
            "https://app.attio.com/oauth/token",
            data={
                "grant_type": "authorization_code",
                "client_id": settings.attio_client_id,
                "client_secret": settings.attio_client_secret,
                "redirect_uri": settings.attio_redirect_uri,
                "code": code,
            },
        )

    if response.status_code != 200:
        logger.error("Attio token exchange failed: %s", response.text)
        raise HTTPException(
            status_code=400,
            detail="Failed to authenticate with Attio. Please try again.",
        )

    tokens = response.json()

    # Attio tokens don't expire — no refresh_token or expires_in
    connection_data = {
        "user_id": user_id,
        "service": "attio",
        "access_token": tokens["access_token"],
        "refresh_token": None,
        "token_expires_at": None,
        "metadata": {},
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }

    existing = (
        supabase.table("connections")
        .select("id")
        .eq("user_id", user_id)
        .eq("service", "attio")
        .execute()
    )

    if existing.data:
        supabase.table("connections").update(connection_data).eq(
            "id", existing.data[0]["id"]
        ).execute()
    else:
        supabase.table("connections").insert(connection_data).execute()

    redirect_url = f"{settings.frontend_url}/connections?connected=attio"
    return RedirectResponse(url=redirect_url)


# ---------------------------------------------------------------------------
# Zoho OAuth
# ---------------------------------------------------------------------------

ZOHO_SCOPES = [
    "ZohoCRM.modules.contacts.ALL",
    "ZohoCRM.modules.accounts.ALL",
    "ZohoCRM.modules.deals.ALL",
    "ZohoCRM.modules.notes.ALL",
]


@router.get("/zoho")
async def zoho_auth(
    user: Any = Depends(get_current_user),
    settings: Settings = Depends(get_settings),
) -> RedirectResponse:
    """Redirect the user to Zoho's OAuth consent screen."""
    params = {
        "scope": ",".join(ZOHO_SCOPES),
        "client_id": settings.zoho_client_id,
        "response_type": "code",
        "access_type": "offline",
        "redirect_uri": settings.zoho_redirect_uri,
        "state": _sign_oauth_state(user.id, settings.supabase_service_role_key),
    }
    url = f"https://accounts.zoho.com/oauth/v2/auth?{urllib.parse.urlencode(params)}"
    return RedirectResponse(url=url)


@router.get("/zoho/callback")
async def zoho_callback(
    code: str = Query(...),
    state: str = Query(""),
    settings: Settings = Depends(get_settings),
    supabase: Client = Depends(get_supabase),
    accounts_server: str = Query("https://accounts.zoho.com", alias="accounts-server"),
    location: str = Query("us"),
) -> RedirectResponse:
    """Exchange the Zoho auth code for tokens and store the connection.

    Zoho returns accounts-server and location params in the callback to
    identify the user's data center. We store these for token refresh.
    """
    user_id = _verify_oauth_state(state, settings.supabase_service_role_key)

    # Validate accounts_server is a legitimate Zoho domain (prevent SSRF)
    allowed_zoho_hosts = {
        "accounts.zoho.com", "accounts.zoho.eu", "accounts.zoho.in",
        "accounts.zoho.com.cn", "accounts.zoho.com.au", "accounts.zoho.jp",
    }
    try:
        parsed_server = urllib.parse.urlparse(accounts_server)
        if parsed_server.hostname not in allowed_zoho_hosts:
            raise HTTPException(
                status_code=400, detail="Invalid Zoho accounts server"
            )
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid Zoho accounts server")

    # Exchange code for tokens — use the user's accounts server
    async with httpx.AsyncClient(timeout=15.0) as client:
        response = await client.post(
            f"{accounts_server}/oauth/v2/token",
            data={
                "grant_type": "authorization_code",
                "client_id": settings.zoho_client_id,
                "client_secret": settings.zoho_client_secret,
                "redirect_uri": settings.zoho_redirect_uri,
                "code": code,
            },
        )

    if response.status_code != 200:
        logger.error("Zoho token exchange failed: %s", response.text)
        raise HTTPException(
            status_code=400,
            detail="Failed to authenticate with Zoho. Please try again.",
        )

    tokens = response.json()
    expires_at = (
        datetime.now(timezone.utc) + timedelta(seconds=tokens.get("expires_in", 3600))
    ).isoformat()

    api_domain = tokens.get("api_domain", "https://www.zohoapis.com")

    connection_data = {
        "user_id": user_id,
        "service": "zoho",
        "access_token": tokens["access_token"],
        "refresh_token": tokens.get("refresh_token"),
        "token_expires_at": expires_at,
        "metadata": {
            "accounts_server": accounts_server,
            "api_domain": api_domain,
            "location": location,
        },
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }

    existing = (
        supabase.table("connections")
        .select("id")
        .eq("user_id", user_id)
        .eq("service", "zoho")
        .execute()
    )

    if existing.data:
        supabase.table("connections").update(connection_data).eq(
            "id", existing.data[0]["id"]
        ).execute()
    else:
        supabase.table("connections").insert(connection_data).execute()

    redirect_url = f"{settings.frontend_url}/connections?connected=zoho"
    return RedirectResponse(url=redirect_url)
